export const FETCH_COMPANY_DETAILS_REQUEST =
  "FETCH_COMPANY_DETAILS_REQUEST" as const;
export const FETCH_COMPANY_DETAILS_SUCCESS =
  "FETCH_COMPANY_DETAILS_SUCCESS" as const;
export const FETCH_COMPANY_DETAILS_FAILURE =
  "FETCH_COMPANY_DETAILS_FAILURE" as const;
