export const FETCH_STOCKS_REQUEST = "FETCH_STOCKS_REQUEST" as const;
export const FETCH_STOCKS_SUCCESS = "FETCH_STOCKS_SUCCESS" as const;
export const FETCH_STOCKS_FAILURE = "FETCH_STOCKS_FAILURE" as const;

export const ADD_STOCK_TO_PORTFOLIO = "ADD_STOCK_TO_PORTFOLIO" as const;
export const DELETE_STOCK_FROM_PORTFOLIO =
  "REMOVE_STOCK_FROM_PORTFOLIO" as const;
